import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar/Navbar'
import Link from 'next/link'
import { Aboreto } from '@next/font/google';

const inter = Inter({ subsets: ['latin'] })
const aboretoFont = Aboreto({weight:"400", style:"normal", subsets:["latin"]});
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <section className={styles.main}>
        <div className={styles.main_message_container}>
        <h1 className={aboretoFont.className}>A tool made for artists <br/> by artists</h1>
        <h2>+250 artists trust us</h2>
        <Link href="">Join us as an artist</Link>
        </div>
        <div className={styles.image_container}>
          <Image width={420} height={600} priority src="/images/main-photo.jpg" alt="Image/Video?"/>
        </div>
      </section>
      <div className={styles.branches_logo_container}>
        <Image src="/images/etude-mimosza-derri.svg" alt="Logo mimosza" width={250} height={100}/>
        <Image src="/images/bcimmo.svg" alt="Logo mimosza" width={250} height={100}/>
        <Image src="/images/carrosserie.svg" alt="Logo mimosza" width={250} height={100}/>
        <Image src="/images/adele.svg" alt="Logo mimosza" width={250} height={100}/>
      </div>
    </>
  )
}
